### PR TITLE
add boards filtered by idf target

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

Filter OpenOCD board by IDF_TARGET

Fixes VSC-1240

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "Select OpenOCD Board configuration"
2. Execute action.
3. Observe results. Should only see board by current IDF_TARGET

- Expected behaviour:

- Expected output:

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

**Test Configuration**:
* ESP-IDF Version:
* OS (Windows,Linux and macOS):

## Dependent components impacted by this PR:

- Component 1
- Component 2

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by kolipakakondal — COMMENTED** [review]
Thanks @brianignacio5 , this is a good enhancement.

Screenshot 2023-11-20 at 6 57 42 PM

With [this](https://gitlab.espressif.cn:6688/idf/openocd-esp32/-/merge_requests/460), the order will also be changed.

**Comment by kolipakakondal** [comment]
Hi @AndriiFilippov Please verify

**Comment by brianignacio5** [comment]
Sorry @AndriiFilippov but I'll fix this issue in the https://github.com/espressif/vscode-esp-idf-extension/pull/1013 too because is not related to the changes in this PR.

Have you tested the `ESP-IDF: Select OpenOCD Board configuration` command to see changes here ?

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

UI update:  please, make this window static: 

image

**Comment by brianignacio5** [comment]
> @brianignacio5 hi !
> 
> UI update: please, make this window static:
> 
> image

Fixed in https://github.com/espressif/vscode-esp-idf-extension/pull/1035/commits/86412788d14ce750c37203c37038ec54516025e6

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

LGTM 👍

**Pull request merged**
