### PR TITLE
use static monitor terminal

### LINKED ISSUE #1132: [Feature Request]: Enable Monitor output to survive restart when in New Window (VSC-1292)
Hi,

I like putting the ESP-IDF monitor into a new window on another monitor rather than having it at the bottom of the main window along with the terminal etc. This way I can see a longer output without having to scroll. I believe this is a new feature in the latest release of Vscode.

To put the monitor into a new window right click on the "ESP-IDF Monitor" title on the right side of the monitor window and select 'Move Terminal into New Window". Then move the window onto another screen.

The problem I encounter is that every time I "build, flash and monitor' my code the monitor window disappears and a new one opens in the main window again. I do the same thing with the build output window, and it doesn't reset every time I build.

This also happens if I just click on the "ESP-IDF Monitor Device" button.

Please change the way the monitor works so its window is not reset every time I "build, flash and monitor', or open it.

Thanks!

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

Please include a summary of the change and which issue is fixed.

Fixes #1132 

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "ESP-IDF: Monitor". Click on "ESP-IDF: Build, flash and monitor". Monitor terminal should be reused and the same.
2. 

## How has this been tested?

Manual testing of above.

**Test Configuration**:
* ESP-IDF Version: 5.2
* OS (Windows,Linux and macOS): macOS

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by Fabricio-ESP** [comment]
Unexpected behavior observed during testing.

System OS: Windows
Description: If the monitor terminal is open on a second window and the user closes that window, any attempts to restart the monitor terminal fails, it is necessary to close VSCode and open it again.

Steps to reproduce:
1- Open a project, set the serial port and target to the Espressif device, build and flash the application.
2- Open the monitor terminal on VSCode.
3- On the terminal tab inside VSCode, on the right column, right click the line "ESP-IDF Monitor" and select "Move Terminal into New Window".
4- Confirm monitor can be restarted without closing the newly created window.
5- Close the monitor window created on step 3. The window will be moved to the main VSCode interface.
6- Close the monitor tab created inside VSCode.
7- Any further attempt to start the ESP-IDF Monitor fails.

Expected behavior:
VSCode would start a new window for the monitor terminal if the previous window was closed.

Notes:
Released build would start a new window and close the previous window if it was opened.

**Comment by brianignacio5** [comment]
I can reproduce the issue when you close the window but if you right click the Monitor on a new window and click Close and try to launch a new monitor it will work.

It seems to be an issue with vscode not disposing this terminal in the use case you mention. I've open a GitHub issue in vscode repository for them to fix. https://github.com/microsoft/vscode/issues/227936

**Comment by Fabricio-ESP** [comment]
# Completed testing.

Tested on Windows 11, Ubuntu 22.04 and MacOS14.
Successfully moved terminal to external window, stopped and restarted the task without it opening a new terminal.
Same behavior as when the terminal is still run within the main VSCode window, the same terminal is reused. If closed when triggering the command to monitor the device a new terminal task is started.

**Review by Fabricio-ESP — APPROVED** [review]

**Review by radurentea — APPROVED** [review]
LGTM

**Pull request merged**
