### PR TITLE
add esp home kit sdk as framework

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

This PR add the `ESP-IDF: Install ESP-HomeKit-SDK` command and `idf.espHomeKitSdkPath` and `idf.espHomeKitSdkPathWin` configuration settings to save this framework.

## Type of change

- New feature (non-breaking change which adds functionality)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "ESP-IDF: Install ESP-HomeKit-SDK" command
2. Select directory to clone the repository into and save it in `idf.espHomeKitSdkPath` or `idf.espHomeKitSdkPathWin` configuration setting.
3. Observe results. The repository should be cloned to the given location.
4. Try `ESP-IDF: Show Examples`, observe the ESP-HomeKit-SDK in the dropdown list, select it and see examples from this framework.
5. Create a project from this example and build it. it should built properly.

**Test Configuration**:
* ESP-IDF Version: 5.0
* OS (Windows,Linux and macOS): macOS

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [x] Added Documentation
- [x] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

Tested under: 
OS - Windows 10 
ESP-IDF: v5.1.2 

able to install "ESP-IDF: Install ESP-HomeKit-SDK"  but could not see examples in "ESP-IDF: Show Examples"

image

**Review by radurentea — CHANGES_REQUESTED** [review]
There are some small changes related to typos

**Comment by brianignacio5** [comment]
> @brianignacio5 hi !
> 
> Tested under: OS - Windows 10 ESP-IDF: v5.1.2
> 
> able to install "ESP-IDF: Install ESP-HomeKit-SDK" but could not see examples in "ESP-IDF: Show Examples"
> 
> image

This is fixed. PTAL

**Comment by brianignacio5** [comment]
> @brianignacio5 hi !
> 
> "ESP-IDF: Install ESP-HomeKit-SDK" command works ✔️ Do see "idf.espHomeKitSdkPath" or "idf.espHomeKitSdkPathWin" configuration setting added to settings.json file ✔️ ESP-IDF: Show Examples, observe the ESP-HomeKit-SDK in the dropdown list ✔️ Create project ✔️ Build project ⛔
> 
> ```
> -- Found Git: C:/Users/AndriiFilippov/.espressif/tools/idf-git/2.39.2/cmd/git.exe (found version "2.39.2.windows.1")
> -- Component directory C:/Users/AndriiFilippov/.espressif/esp-homekit-sdk/components/homekit does not contain a CMakeLists.txt file. No component will be added
> CMake Error at C:/Users/AndriiFilippov/e/esp-idf-v5.1.2/tools/cmake/project.cmake:349 (message):
>   Directory specified in EXTRA_COMPONENT_DIRS doesn't exist:
>   C:/Users/AndriiFilippov/common
> Call Stack (most recent call first):
>   C:/Users/AndriiFilippov/e/esp-idf-v5.1.2/tools/cmake/project.cmake:433 (__project_init)
>   CMakeLists.txt:14 (project)
> 
> 
> -- Configuring incomplete, errors occurred!
> 
>  *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -B c:\Users\AndriiFilippov\project-namedr8686786\build -S c:\Users\AndriiFilippov\project-namedr8686786" terminated with exit code: 1.
> ```

This a problem of the example project itself, unrelated to this PR. The CMakeLists.txt has a path that is relative to original repository which should be updated. Replace `${CMAKE_CURRENT_LIST_DIR}/../common` to `${HOMEKIT_PATH}/examples/common` in the root directory CMakeLists.txt

**Review by AndriiFilippov — APPROVED** [review]

**Pull request merged**
