### PR TITLE
Show Rainmaker LoggedIn User's Info (VSC-498)

### LINKED ISSUE #232: [Feature Request]: Show info about rainmaker account (VSC-496)
I have more than one rainmaker account, at the moment I can add only one, and in the interface, I cannot see which account I'm using at the moment.

I would like to have a way to understand which account I'm using now.

A better solution is to support more than one account t a time.

image

### PR DESCRIPTION
**Pull request by pwmb**
Now you can view the loggedin user name (or email) in the rainmaker view

Closes #232

### CODE REVIEW

**Comment by brianignacio5** [comment]
I tested but for some reason on extension activation, when I switch to ESP-IDF Explorer, rainmaker doesn't show any option and got this error:
Screen Shot 2020-12-14 at 8 43 44 PM

**Review by kumekay — APPROVED** [review]
Works great for me for all ways to authenticate:
username, github, google, apple

I've tried both on WSL and windows natively

**Comment by kumekay** [comment]
> I tested but for some reason on extension activation, when I switch to ESP-IDF Explorer, rainmaker doesn't show any option and got this error:
> Screen Shot 2020-12-14 at 8 43 44 PM
> No related log output.

I didn't manage to reproduce this behavior

**Comment by pwmb** [comment]
> > I tested but for some reason on extension activation, when I switch to ESP-IDF Explorer, rainmaker doesn't show any option and got this error:
> > Screen Shot 2020-12-14 at 8 43 44 PM
> > No related log output.
> 
> I didn't manage to reproduce this behavior

You will get this error, if your session id is invalid (after long time)... will fix this issue, thanks @brianignacio5 for noticing

**Pull request merged**
