### PR TITLE
Update debug adapter (VSC-429)

### PR DESCRIPTION
**Pull request by an-dr**
- Updated debug adapter with a new version with coredump and postmortem support
- Re-added adapter as a submodule (https://github.com/espressif/esp-debug-adapter)
- Updated arguments in the adapter test

### CODE REVIEW

**Review by brianignacio5 — APPROVED** [review]
LGTM

**Review by pwmb — APPROVED** [review]

**Comment by pwmb** [comment]
@an-dr Please update the CI for python dependency download step.

One question, not now, but in future once we have #139 merged, can we add the debug adapter as pip package instead of sub-module ? Since #139 have a provision to maintain extension's own `requirements.txt` file

**Review by pwmb — CHANGES_REQUESTED** [review]
Please update the CI for python dependency download step.

**Comment by pwmb** [comment]
@an-dr One question, not now, but in future once we have #139 merged, can we add the debug adapter as pip package instead of sub-module ? Since #139 have a provision to maintain extension's own `requirements.txt` file

**Review by pwmb — APPROVED** [review]
LGTM

**Pull request merged**
