### PR TITLE
Filter serial devices by default and allow user to disable chip id in serial port list

### LINKED ISSUE #1274: Opening the port list is always slow (VSC-1458)
### OS

Windows

### Operating System version

macOS 12.7.6

### Visual Studio Code version

1.90.0

### ESP-IDF version

5.4.0

### Python version

3.12.3

### Doctor command output

[report.txt](https://github.com/user-attachments/files/16537319/report.txt)

### Extension

_No response_

### Description

Every time you click the Select Serial Port command (especially the first time), loading the serial port list is slow, the ls /dev command and platformio are very fast, complete in 1 second, I think this is a problem.

https://github.com/user-attachments/assets/08ff4a66-3af5-4492-89c9-bfb9cbe5f8e3

### Expect

Just like `ls /dev` or platformio, it shows the serial ports on the computer in one second.

https://github.com/user-attachments/assets/309d827e-4c3c-41ca-9d18-1585edc9da3f

https://github.com/user-attachments/assets/58a8c605-b111-44e6-b824-e462634b55d5

### Debug Message

```plain
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

Add `idf.enableSerialPortChipIdRequest` and `idf.useSerialPortVendorProductFilter` which are set true by default.

Now the serial ports listed with the **ESP-IDF: Select port to use** command will only show know USB serial ports by filtering them with productID and vendorID.  This can be disabled with `"idf.useSerialPortVendorProductFilter": false` in settings.json

esptool.py chip_id is executed when running the previous command to get the chip name and show it in the list. This can be disabled with `"idf.enableSerialPortChipIdRequest": false` in settings.json.

Add `idf.usbSerialPortFilters` for user to define the list of USB PID VID filters.

Fixes #1274

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "**ESP-IDF: Select port to use** ". Now only Espressif devices should be shown by default.
2. Set `"idf.useSerialPortVendorProductFilter": false` and Click on "**ESP-IDF: Select port to use** ". Now all serial ports will be shown. If set true, the behavior is back as step 1.
3. Set `"idf.enableSerialPortChipIdRequest": false` and Click on "**ESP-IDF: Select port to use** ".  Now the esptool.py chip_id is not executed and the chip name is not shown in list. If set true, the behavior is same as step 1.

- Expected behaviour:

- Expected output:

## How has this been tested?

Manual testing with steps above.

**Test Configuration**:
* ESP-IDF Version: 5.2.2
* OS (Windows,Linux and macOS): macOS

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by radurentea — APPROVED** [review]
LGTM

**Comment by radurentea** [comment]
Hi @Fabricio-ESP,

Please take a look

**Comment by Fabricio-ESP** [comment]
Having some troubles to get the correct data from the connected USB devices.
From the parameters provided, "UseSerialPortVendorProductFilter" is disabled by default. (updated official VSCode installation with the test binaries, on a Windows 11 machine).

image

Enabling filter, it shows the WROVER module only, the devices using Silicon Labs USB converters are filtered out.

image
image

Selecting the option to detect the chip id does not change this behavior.

image


Also observed that when the option to read the chip ID is selected, the detection of the WROVER module is intermitent.

image
image

**Comment by brianignacio5** [comment]
I've added USB CDC-ACM in the default list. Could you try again @Fabricio-ESP  ?

Regarding the intermittent issue, do you see any related error in the extension log/ doctor command output ? It might be also be a timeout or connection issue.

**Comment by Fabricio-ESP** [comment]
Confirmed USB devices are not properly selected and filtered. 
Tested on Windows 11 and Ubuntu with ESP32, ESP32-C6 and ESP32-S3 devkits.

The parameters to filter the devices is disabled by default.

**Review by Fabricio-ESP — APPROVED** [review]
No issues observed on the last build.

**Pull request merged**
