### PR TITLE
add space validation doctor cmd setup wizard

### LINKED ISSUE #742: [Bug Report]: using any spaces in filepath breaks ESP-IDF usage (VSC-921)
tl/dr; Fails horribly if you have any spaces in your filepath.

As someone that is still new with VS Code and with VSC+ESP-IDF, I had a frustrating time getting VSC+ESP-IDF to work.  After spending about three hours, I finally got it to work.   

There is one critical aspect in my experience: I had a space in my file path.  Because I wanted to use ESP-IDF with a project for a client, the working directory included the client name which has a space in it.

This apparently was breaking the device-target selection and menuconfig operation.  The error messages were cryptic and generally unhelpful.  When trying to debug the menuconfig not working, the output session for menuconfig would close before I could read its contents.

I uninstalled and reinstalled the ESP-IDF extension a few times.  I even uninstalled my standard ESP-IDF (the one launched from the desktop) and tried again.

It was only when I tried to open the example in a new directory that it worked.  And it wasn't the path length.

That was three (or more) hours down the drain.

Perhaps it serves me right to use spaces in a path with coding tools.  But I've had Arduino projects under the same client's directory which worked fine with Arduino-ESP32 (via Arduino), so I had no reason to believe that the VSC ESP32 tools wouldn't work in that same folder.

Now that I've gotten past this single detail that was proving to be a critical tripping point, I happily watched the build process run and build successfully.

To reproduce this, go through the steps of setting up the example Blink project, but in a directory with a space somewhere in the filepath.

Setting device-target yields:
image
`-- Building ESP-IDF components for target esp32
-- Project sdkconfig file C:/Users/joech/esp/x 1/blink/sdkconfig
Traceback (most recent call last):
  File "C:/Users/joech/esp/esp-idf/tools/kconfig_new/confgen.py", line 640, in <module>
    main()
  File "C:/Users/joech/esp/esp-idf/tools/kconfig_new/confgen.py", line 260, in main
    config = kconfiglib.Kconfig(args.kconfig)
  File "C:\Espressif\python_env\idf4.4_py3.8_env\lib\site-packages\kconfiglib.py", line 947, in __init__
    self._init(filename, warn, warn_to_stderr, encoding)
  File "C:\Espressif\python_env\idf4.4_py3.8_env\lib\site-packages\kconfiglib.py", line 1085, in _init
    self._parse_block(None, self.top_node, self.top_node).next = None
  File "C:\Espressif\python_env\idf4.4_py3.8_env\lib\site-packages\kconfiglib.py", line 2982, in _parse_block
    prev = self._parse_block(None, parent, prev)
  File "C:\Espressif\python_env\idf4.4_py3.8_env\lib\site-packages\kconfiglib.py", line 2970, in _parse_block
    raise KconfigError(
kconfiglib.KconfigError: C:/Users/joech/esp/x 1/blink/build/kconfigs_projbuild.in:6: 'C:/Users/joech/esp/x' not found (in 'source "C:/Users/joech/esp/x"'). Check that environment variables are set correctly (e.g. $srctree, which is unset or blank). Also note that unset environment variables expand to the empty string.
CMake Error at C:/Users/joech/esp/esp-idf/tools/cmake/kconfig.cmake:266 (message):
  Failed to run confgen.py`

Attempting to run menuconfig yields a progress-bar that gets stuck:
image

I would have expected things to work with spaces in the filepath; or at least some kind of warning/error complaining about the space.

FWIW, this is on Windows 10 with VSC 1.68.0, ESP-IDF 1.4.0

### LINKED ISSUE #751: [Bug Report]: ESP-IDF does not work with user dirs with space in name (VSC-929)
**Pre Bug Report Checklist**
Before reporting any bug please make sure of these points.

- [ ] Make sure you have searched for existing bugs and features request before you post an issue.
- [ ] This is a bug report for the ESP-IDF Visual Studio Code extension and **not** an ESP-IDF bug report.
- [ ] I've read the docs and found no information that could have helped solving the issue.

**Describe the bug**
After install of all components using VS Studio Code, and adding all dependencies, projects cannot compile, cannot select serial port, or monitor etc as all commands crash out as they do not escape spaces in directories.

**To Reproduce**
Install as normal, with user that has a space in directory name (Windows 10).

**Expected behavior**
Expected examples to compile, able to select port etc.

**Screenshots**

**Environment (please complete the following information):**

- Windows 10
- VSCode Version: 1.68.1
- ESP-IDF Version: unknown - latest installed today
- Python Version: 3.8

> **NOTE**: You can use the `ESP-IDF: Doctor command` to generate a report of your configuration in your clipboard which you can copy here.

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.19043 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python310\Scripts\;C:\Python310\;C:\Program Files\Oculus\Support\oculus-runtime;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Microchip\xc8\v2.31\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\Scott Porter\AppData\Local\Microsoft\WindowsApps;;C:\Users\Scott Porter\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Scott Porter\AppData\Roaming\npm 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.68.1 
Visual Studio Code language en 
Visual Studio Code shell C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.4.0 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:\Users\Scott Porter\esp\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
Custom extra paths (idf.customExtraPaths) C:\Users\Scott Porter\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin;C:\Users\Scott Porter\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s2-elf\bin;C:\Users\Scott Porter\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s3-elf\bin;C:\Users\Scott Porter\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch3-8.4.0\riscv32-esp-elf\bin;C:\Users\Scott Porter\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\Users\Scott Porter\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\Users\Scott Porter\.espressif\tools\cmake\3.20.3\bin;C:\Users\Scott Porter\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin;C:\Users\Scott Porter\.espressif\tools\ninja\1.10.2;C:\Users\Scott Porter\.espressif\tools\idf-exe\1.0.3;C:\Users\Scott Porter\.espressif\tools\ccache\4.3\ccache-4.3-windows-64;C:\Users\Scott Porter\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"C:\\Users\\Scott Porter\\.espressif\\tools\\openocd-esp32\\v0.11.0-esp32-20211220/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1"}
Virtual env Python Path (idf.pythonBinPath) C:\Users\Scott Porter\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM1
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/esp32_devkitj_v1.cfg,board/esp32-wrover.cfg
ESP-IDF Tools Path (idf.toolsPath) C:\Users\Scott Porter\.espressif
Git Path (idf.gitPath) C:\Users\Scott Porter\.espressif\tools\idf-git\2.30.1\cmd\git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-IDF Custom extra paths
Access to C:\Users\Scott Porter\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin: true
Access to C:\Users\Scott Porter\.espressif\tools\xtensa-esp32s2-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s2-elf\bin: true
Access to C:\Users\Scott Porter\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32s3-elf\bin: true
Access to C:\Users\Scott Porter\.espressif\tools\riscv32-esp-elf\esp-2021r2-patch3-8.4.0\riscv32-esp-elf\bin: true
Access to C:\Users\Scott Porter\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin: true
Access to C:\Users\Scott Porter\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin: true
Access to C:\Users\Scott Porter\.espressif\tools\cmake\3.20.3\bin: true
Access to C:\Users\Scott Porter\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin: true
Access to C:\Users\Scott Porter\.espressif\tools\ninja\1.10.2: true
Access to C:\Users\Scott Porter\.espressif\tools\idf-exe\1.0.3: true
Access to C:\Users\Scott Porter\.espressif\tools\ccache\4.3\ccache-4.3-windows-64: true
Access to C:\Users\Scott Porter\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 4.4.1
Python version 3.8.7
Python's pip version 20.3.3
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages undefined
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages undefined
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages undefined
----------------------------------------------------------- Latest error -----------------------------------------------------------------
Latest error at Command failed: C:\Users\Scott Porter\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe -m pip list --format json
'C:\Users\Scott' is not recognized as an internal or external command,
operable program or batch file.

--------------------------------------------------------------------------------------------------------------------------------------------

In Visual Studio Code select menu `View` -> `Output` -> ESP-IDF, ESP-IDF Debug Adapter, Heap Trace, OpenOCD and SDK Configuration Editor. (doesn't work)

> **NOTE:** Use `idf.openOcdDebugLevel` configuration setting to 3 or more to show debug logging in OpenOCD server output. (doesn't work)

> **NOTE:** Use `logLevel` in your <project-directory>/.vscode/launch.json to 3 or more to show more debug adapter output.

Please share the output of the channel related to your issue. For example ESP-IDF is used mostly for the extension setup process output.

**Logs**
Please share the log file which can be obtained from:

PS Z:\esp-idf\hello_world\hello_world> C:\Users\Scott Porter\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:\Users\Scott Porter\esp\esp-idf\tools\idf.py -p COM1 monitor
C:\Users\Scott : The term 'C:\Users\Scott' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ C:\Users\Scott Porter\.espressif\python_env\idf4.4_py3.8_env\Scripts\ ...
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Scott:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS Z:\esp-idf\hello_world\hello_world>

**Extension Configuration settings**
Open Command Palette (F1 or View Menu -> Command Palette) and type `Preferences: Open Settings (JSON)` or use `{CURRENT_PROJECT}/.vscode/settings.json` to get the following extension configuration settings value:

- `idf.espIdfPath` (MacOS or Linux) or `idf.espIdfPathWin` (Windows) also called `Path to locate ESP-IDF framework (IDF_PATH)` in `Preferences: Open Settings (UI)`.
- `idf.pythonBinPath` (MacOS or Linux) or `idf.pythonBinPathWin` (Windows) also called `Python absolute binary path used to execute ESP-IDF Python Scripts` in `Preferences: Open Settings (UI)`.
- `idf.openOcdConfigs` also called `List of configuration files inside OpenOCD Scripts directory` in `Preferences: Open Settings (UI)`.
- `idf.customExtraPaths` also called `Paths to be appended to PATH` in `Preferences: Open Settings (UI)`.
- `idf.customExtraVars` also called `Variables to be added to system environment variables` in `Preferences: Open Settings (UI)`.
- `idf.adapterTargetName` also called `Target name for ESP-IDF Debug Adapter` in `Preferences: Open Settings (UI)`.
- `idf.customAdapterTargetName` is used when `idf.adapterTargetName` is set to `custom`.

**Additional context**

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

Please include a summary of the change and which issue is fixed.

Fix #742
Fix #751 

## Type of change

Add validation of spaces in path in both the setup wizard and the doctor command.

- Bug fix (non-breaking change which fixes an issue)

## How has this been tested?

Manual testing observing result in doctor command and the Setup Wizard with wrong and good paths.

**Test Configuration**:
* ESP-IDF Version: v5.0
* OS (Windows,Linux and macOS): MacOS

## Dependent components impacted by this PR:

No components impacted.

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [x] Added Documentation
- [ ] Added Unit Test
- [x] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by dordnung** [comment]
Hey,
with this Pull Request my GIT location will not be accepted anymore and I get the error: "C:\Program Files\Git\cmd\git.exe has spaces. Use another location. (GIT_PATH_WITH_SPACES)". But before it worked with spaces without any problem.

**Comment by brianignacio5** [comment]
Any reason not to use the embed git in `${IDF_TOOLS_PATH}\tools\idf-git\2.3.1\cmd\git.exe` ?

If your build and flash was working fine before we could remove this git space validation, I thought it was breaking the build task.

**Comment by dordnung** [comment]
Ah you were faster than I edited my comment. As mentioned **idf.gitPathWin** is automatically set by the setup tool to an internal git in .espressif folder. But when downloading the tools it will still take the GIT in my PATH variable. In 1.4.0 **idf.gitPathWin** is not available but **idf.gitPath** will be set and used (which seems to work). Maybe something is wrong there

**Comment by brianignacio5** [comment]
Thanks for reporting this @dordnung . You are probably using the Advanced mode in the Setup wizard right ?

I've made some changes in [this PR](https://github.com/espressif/vscode-esp-idf-extension/pull/783) to use the embed git for this case. Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/333927493.zip) ?

[how to Install extension from vsix](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by dordnung** [comment]
Thanks for the fast fix and sorry for the late testing, but it works fine with this fix

**Pull request merged**
