### PR TITLE
:bug: Fix python venv install wheel issue in Linux (VSC-348)

### LINKED ISSUE #105: Configure ESP-IDF extension fails at the stage of downloading tools at Python 3.8 (VSC-329)
**Describe the bug**
Hi guys! I'm preparing a debugging training right now and experimenting with the clean installation of the extension.

I've faced with the bug breaking the configuration process with the Python 3.8.2 (Python 2 works).

**To Reproduce**
- Create a new project
- Call >ESP-IDF: Configure ESP-IDF extension
- At the step of downloading tools you'll get the error

**Expected behavior**
Installing of the tools and appearing of the button "Next"

**Screenshots**
Screenshot from 2020-05-18 13-42-31

**Environment (please complete the following information):**

- OS Name & Version: Ubuntu 20.04
- VSCode Version: 1.45.1
- ESP-IDF Version: 4.2
- Python Version: 3.8.2

**Logs**
[esp-idf_output_panel.log](https://github.com/espressif/vscode-esp-idf-extension/files/4643907/esp-idf_output_panel.log)
[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/4643908/esp_idf_vsc_ext.log)

### PR DESCRIPTION
**Pull request by brianignacio5**
For Python > 3.3, we use `venv` since it the official Python virtual environments module. The thing is, for Linux users it seems to not include `wheel` from the system wide Python within the virtual environment. 

We added an step to install wheel in the virtualenv before installing requirements.txt

Should fix #105

### CODE REVIEW

**Comment by an-dr** [comment]
It seems not solved for me. and even a bit more broken then it was)

For python 2 `esp_idf_vsc_ext.log`:
```
{"message":"Command failed: git describe --tags\nfatal: not a git repository (or any of the parent directories): .git\n","stack":"Error: Command failed: git describe --tags\nfatal: not a git repository (or any of the parent directories): .git\n\n\tat ChildProcess.exithandler (child_process.js:308:12)\n\tat ChildProcess.emit (events.js:203:13)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:203:13)\n\tat Pipe.<anonymous> (net.js:588:12)","level":"error","timestamp":"2020-06-09T09:27:42.386Z"}
{"message":"Python 2.7.18rc1\n","stack":"Error: Python 2.7.18rc1\n\n\tat /home/agramakov/.vscode/extensions/espressif.esp-idf-extension-0.2.2/dist/extension.js:1:6391\n\tat ChildProcess.exithandler (child_process.js:299:7)\n\tat ChildProcess.emit (events.js:203:13)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Socket.<anonymous> (internal/child_process.js:430:11)\n\tat Socket.emit (events.js:203:13)\n\tat Pipe.<anonymous> (net.js:588:12)","level":"error","timestamp":"2020-06-09T09:28:27.274Z"}
{"message":"DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support\nWARNING: You are using pip version 20.1; however, version 20.1.1 is available.\nYou should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.\n","stack":"Error: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support\nWARNING: You are using pip version 20.1; however, version 20.1.1 is available.\nYou should consider upgrading via the '/usr/bin/python -m pip install --upgrade pip' command.\n\n\tat /home/agramakov/.vscode/extensions/espressif.esp-idf-extension-0.2.2/dist/extension.js:1:6391\n\tat ChildProcess.exithandler (child_process.js:299:7)\n\tat ChildProcess.emit (events.js:203:13)\n\tat maybeClose (internal/child_process.js:1021:16)\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)","level":"error","timestamp":"2020-06-09T09:28:27.789Z"}
{"message":"spawn /bin/sh ENOENT","stack":"Error: spawn /bin/sh ENOENT\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n\tat onErrorNT (internal/child_process.js:456:16)\n\tat processTicksAndRejections (internal/process/task_queues.js:77:11)","level":"error","timestamp":"2020-06-09T09:28:27.940Z"}
```
Screenshot from 2020-06-09 11-32-26


For python3 `esp_idf_vsc_ext.log`:
```
{"message":"spawn /bin/sh ENOENT","stack":"Error: spawn /bin/sh ENOENT\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n\tat onErrorNT (internal/child_process.js:456:16)\n\tat processTicksAndRejections (internal/process/task_queues.js:77:11)","level":"error","timestamp":"2020-06-09T09:34:30.160Z"}

```

Screenshot from 2020-06-09 11-34-59

**Comment by brianignacio5** [comment]
This seems to be related to the shell executable being used. Isn't it `/bin/sh`? And also, is there any virtual environment enabled in your vscode already? (For example, platformIO ?)

**Comment by an-dr** [comment]
@brianignacio5 right now, `~` is not expands, but used as a name of folder 

Screenshot from 2020-06-17 10-21-57

**Comment by an-dr** [comment]
@brianignacio5 using the full and  on python 2.7

Screenshot from 2020-06-17 10-28-46

I'm getting

```
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Exception:
Traceback (most recent call last):
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 302, in run
    check_supported_wheels=not options.target_dir,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 345, in get_requirements
    use_pep517=options.use_pep517
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/constructors.py", line 462, in install_req_from_parsed_requirement
    line_source=parsed_req.line_source,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/constructors.py", line 405, in install_req_from_line
    extras=parts.extras,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 144, in __init__
    self.local_file_path = self.link.file_path
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/models/link.py", line 114, in file_path
    return url_to_path(self.url)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/utils/urls.py", line 51, in url_to_path
    .format(**locals())
ValueError: non-local file URIs are not supported on this platform: u'file://${IDF_PATH}/tools/kconfig_new/esp-windows-curses'
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/bin/python -m pip install --upgrade pip' command.
Command failed: "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/bin/python" -m pip install -r "/mnt/c/esp-idf/requirements.txt"
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Exception:
Traceback (most recent call last):
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 302, in run
    check_supported_wheels=not options.target_dir,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 345, in get_requirements
    use_pep517=options.use_pep517
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/constructors.py", line 462, in install_req_from_parsed_requirement
    line_source=parsed_req.line_source,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/constructors.py", line 405, in install_req_from_line
    extras=parts.extras,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 144, in __init__
    self.local_file_path = self.link.file_path
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/models/link.py", line 114, in file_path
    return url_to_path(self.url)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/utils/urls.py", line 51, in url_to_path
    .format(**locals())
ValueError: non-local file URIs are not supported on this platform: u'file://${IDF_PATH}/tools/kconfig_new/esp-windows-curses'
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/bin/python -m pip install --upgrade pip' command.
Command failed: "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/bin/python" -m pip install -r "/mnt/c/esp-idf/requirements.txt"
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Exception:
Traceback (most recent call last):
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 302, in run
    check_supported_wheels=not options.target_dir,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 345, in get_requirements
    use_pep517=options.use_pep517
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/constructors.py", line 462, in install_req_from_parsed_requirement
    line_source=parsed_req.line_source,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/constructors.py", line 405, in install_req_from_line
    extras=parts.extras,
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 144, in __init__
    self.local_file_path = self.link.file_path
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/models/link.py", line 114, in file_path
    return url_to_path(self.url)
  File "/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/lib/python2.7/site-packages/pip/_internal/utils/urls.py", line 51, in url_to_path
    .format(**locals())
ValueError: non-local file URIs are not supported on this platform: u'file://${IDF_PATH}/tools/kconfig_new/esp-windows-curses'
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/bin/python -m pip install --upgrade pip' command.


The following paths should be added to env PATH
/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/bin:/usr/bin:/home/agramakov/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin:/home/agramakov/.espressif/tools/xtensa-esp32s2-elf/esp-2020r2-8.2.0/xtensa-esp32s2-elf/bin:/home/agramakov/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/home/agramakov/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/home/agramakov/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200420/openocd-esp32/bin


```

**Comment by an-dr** [comment]
@brianignacio5 using a full path with Python 3.8

```
Creating a new Python environment in /home/agramakov/.espressif/python_env/idf4.2_py3.8_env ...



Collecting wheel
  Using cached wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: wheel
Successfully installed wheel-0.34.2


ERROR: Exception:
Traceback (most recent call last):
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 325, in run
    self.populate_requirement_set(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 266, in populate_requirement_set
    for req_to_add in parse_requirements(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 138, in parse_requirements
    req = handle_line(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 201, in handle_line
    return install_req_from_line(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 397, in install_req_from_line
    return InstallRequirement(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 140, in __init__
    self.local_file_path = self.link.file_path
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/models/link.py", line 105, in file_path
    return url_to_path(self.url)
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/utils/urls.py", line 48, in url_to_path
    raise ValueError(
ValueError: non-local file URIs are not supported on this platform: 'file://${IDF_PATH}/tools/kconfig_new/esp-windows-curses'
Command failed: "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/bin/python" -m pip install -r "/mnt/c/esp-idf/requirements.txt"
ERROR: Exception:
Traceback (most recent call last):
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 325, in run
    self.populate_requirement_set(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 266, in populate_requirement_set
    for req_to_add in parse_requirements(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 138, in parse_requirements
    req = handle_line(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 201, in handle_line
    return install_req_from_line(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 397, in install_req_from_line
    return InstallRequirement(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 140, in __init__
    self.local_file_path = self.link.file_path
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/models/link.py", line 105, in file_path
    return url_to_path(self.url)
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/utils/urls.py", line 48, in url_to_path
    raise ValueError(
ValueError: non-local file URIs are not supported on this platform: 'file://${IDF_PATH}/tools/kconfig_new/esp-windows-curses'
Command failed: "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/bin/python" -m pip install -r "/mnt/c/esp-idf/requirements.txt"
ERROR: Exception:
Traceback (most recent call last):
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 325, in run
    self.populate_requirement_set(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 266, in populate_requirement_set
    for req_to_add in parse_requirements(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 138, in parse_requirements
    req = handle_line(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_file.py", line 201, in handle_line
    return install_req_from_line(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/constructors.py", line 397, in install_req_from_line
    return InstallRequirement(
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 140, in __init__
    self.local_file_path = self.link.file_path
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/models/link.py", line 105, in file_path
    return url_to_path(self.url)
  File "/home/agramakov/.espressif/python_env/idf4.2_py3.8_env/lib/python3.8/site-packages/pip/_internal/utils/urls.py", line 48, in url_to_path
    raise ValueError(
ValueError: non-local file URIs are not supported on this platform: 'file://${IDF_PATH}/tools/kconfig_new/esp-windows-curses'


The following paths should be added to env PATH
/home/agramakov/.espressif/python_env/idf4.2_py2.7_env/bin:/usr/bin:/home/agramakov/.espressif/tools/xtensa-esp32-elf/esp-2020r2-8.2.0/xtensa-esp32-elf/bin:/home/agramakov/.espressif/tools/xtensa-esp32s2-elf/esp-2020r2-8.2.0/xtensa-esp32s2-elf/bin:/home/agramakov/.espressif/tools/esp32ulp-elf/2.28.51-esp-20191205/esp32ulp-elf-binutils/bin:/home/agramakov/.espressif/tools/esp32s2ulp-elf/2.28.51-esp-20191205/esp32s2ulp-elf-binutils/bin:/home/agramakov/.espressif/tools/openocd-esp32/v0.10.0-esp32-20200420/openocd-esp32/bin

```

**Comment by an-dr** [comment]
Just to be clear, using of `~` is the cause of `spawn /bin/sh ENOENT` that I've reported earlier

**Comment by brianignacio5** [comment]
Oh yes, we don't support `~` Hmm so IDF_PATH is required in env variable.

**Comment by an-dr** [comment]
@brianignacio5 is it expected behavior with IDF_PATH?

**Comment by brianignacio5** [comment]
From export.sh it can sort of resolve using its current directory but the Windows installer got a fix for this on December 2019 looking at some esp-idf issues. It's probably because is only on latest esp-idf version no one has reported this yet.

**Pull request merged**
