### PR TITLE
Add validation for no ports

### PR DESCRIPTION
**Pull request by radurentea**
## Description

Fixes bug for  "New Project" window.
image

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Use Command "New Project"

- Expected behaviour:
Window should be useable, before this fix, the behaviour was like the one in the screenshot attached above.
- Expected output:

**Test Configuration**:
* ESP-IDF Version: 5.2.1
* OS (Windows,Linux and macOS): Windows

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by brianignacio5 — APPROVED** [review]
LGTM

**Comment by radurentea** [comment]
@AndriiFilippov PTAL

**Comment by AndriiFilippov** [comment]
@radurentea hi !
Tested 
LGTM 👍 

Just noticed that during port selection it try to connect to the board before port is  selected. which is cause this error. it is not critical - everything works, but this will confuse users:


image

**Comment by radurentea** [comment]
I'm not sure why you get this error, I've tested with c6 board and I had no issue. Maybe you don't have the drivers installed for the board?

**Comment by AndriiFilippov** [comment]
ok, I will double check it. 
Lets merge this one

**Pull request merged**
