### PR TITLE
Enhance/esp rainmaker

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

Add ESP-Rainmaker to the extension environment and clone command.

## Type of change

- New feature (non-breaking change which adds functionality)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "Install Esp-rainmaker" to clone asp-rainmaker to a selected location
2. Execute "Open Examples" command and choose esp-rainmaker and create example
3. Create example and build project.
4. Observe results.

- Expected behaviour:

Rainmaker examples can be created from extension and built since rainmaker code is loaded in environment.

- Expected output:

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

**Test Configuration**:
* ESP-IDF Version: 5.0
* OS (Windows,Linux and macOS): macOS

## Dependent components impacted by this PR:

- Component 1
- Component 2

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [x] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by Dont008 — APPROVED** [review]

**Review by radurentea — COMMENTED** [review]
Found a typo, everything else LGTM.

**Comment by RoootNoodle** [comment]
I am new to ESP32 environment and started working with Rainmaker. Did not have any luck with ESP-IDF until this update, thank you!
It will be nice to have a blank Rainmaker example with only one led or  so to be turned on and off

**Comment by brianignacio5** [comment]
You can try the [Get started with ESP-Rainmaker](https://rainmaker.espressif.com/docs/get-started.html) or use the [LED light example](https://github.com/espressif/esp-rainmaker/tree/master/examples/led_light) or examples within the ESP-Rainmaker directory.

If you have configure ESP-Rainmaker in the extension, just click the `ESP-IDF: Show Examples projects` and select the ESP-Rainmaker framework to create project from the ESP-Rainmaker examples.

**Comment by RoootNoodle** [comment]
I did that just after typing the comment!
Is it possible to define custom variables in the sdkcondig file like with the examples?

**Comment by brianignacio5** [comment]
What do you mean about custom variables ? You mean to change sdkconfig values like with the `ESP-IDF: SDK Configuration editor`?

**Comment by RoootNoodle** [comment]
Yes to creat a custom field eg. Relay pin and then being able to change it with the menucofig

**Comment by brianignacio5** [comment]
You can use the `ESP-IDF: SDK Configuration editor` extension command which is basically a web version of menuconfig. The custom fields you could define it in the Kconfig.projbuild and use them in the project, same way as the example does.

**Comment by RoootNoodle** [comment]
Thanks I'll give it a try

**Pull request merged**
