### PR TITLE
Feature/project conf editor

### LINKED ISSUE #671: [Feature Request]: One project - different settings sdkconfig (VSC-861)
I have a working[ project](https://serverdoma.ru/viewtopic.php?f=70&t=1178&start=1740) that I have been developing until recently in the `PlatformIO + VS Code` environment.
The crux of the problem is this:
There is an [LVGL](https://github.com/lvgl/lvgl) library that supports several types of displays, but  not does allow two different displays set in the `sdkconfig` settings. For example, I want to compile 2 firmware for `ESP32` with `ILI9341` and `ILI9341` displays from one project and two more firmware with `ILI9341` and `ILI9341` displays for `ESP32-S2`.
I need 4 different `sdkconfig`.
In `PlatformIO`, it is possible to have several independent `sdkconfig` settings in one project and switch between them with a simple mouse click.
Here is an example of the PlatformIO configuration file
```ini
[platformio]
src_dir = main
include_dir = main/include
description = Radiola-ESP32

[env]
;platform = https://github.com/platformio/platform-espressif32.git
platform = espressif32
framework = espidf
monitor_speed = 115200
debug_tool = esp-prog
upload_protocol = esp-prog
;monitor_filters = direct
monitor_flags =
	--eol
	LF
board_build.partitions = partitions.csv
extra_scripts = 
	pre:pre_extra_script.py
	extra_script.py

[common]
build_flags = 
	-D LV_CONF_INCLUDE_SIMPLE

[env:W1_SSD1306]
board = esp-wrover-kit
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = 
	-D FILENAME=Radiola-2W1_SSD1306
	${common.build_flags}

[env:W1_ILI9341]
board = esp-wrover-kit
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = 
	-D FILENAME=Radiola-2W1_ILI9341
	${common.build_flags}

[env:W1_ILI9488]
board = esp-wrover-kit
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = 
	-D FILENAME=Radiola-2W1_ILI9488
	${common.build_flags}

[env:S2_ILI9341]
board = esp32-s2-saola-1
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = 
	-D FILENAME=Radiola-S2_ILI9341
	${common.build_flags}

[env:S2_ILI9488]
board = esp32-s2-saola-1
build_type = debug
monitor_filters = esp32_exception_decoder
build_flags = 
	-D FILENAME=Radiola-S2_ILI9488
	${common.build_flags}

```
I have no idea how to do this in vscode-esp-idf-extension.

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

Use workspace state to manage multiple settings profiles for the current workspace using the vscode workspace state API.

Add UI to switch between different settings using the `ESP-IDF: Open Project Configuration` and `ESP-IDF: Select project configuration` to choose between different settings profile.

Fix #671 

## Type of change

- New feature (non-breaking change which adds functionality)

## How has this been tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Test A
- Test B

**Test Configuration**:
* ESP-IDF Version: 5.0
* OS (Windows,Linux and macOS): macOS

## Dependent components impacted by this PR:

- Component 1
- Component 2

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [x] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by brianignacio5** [comment]
Hi @SinglWolf Could you please take a look at this.

Tried to implement the project configuration feature. Take a look at the tutorial added here.

**Comment by SinglWolf** [comment]
> Hi @SinglWolf Could you please take a look at this?
> 
> Tried to implement the project configuration feature. Take a look at the tutorial added here.

To be honest, I don't understand what this is about...

**Comment by brianignacio5** [comment]
> > Hi @SinglWolf Could you please take a look at this?
> > Tried to implement the project configuration feature. Take a look at the tutorial added here.
> 
> To be honest, I don't understand what this is about...

Is related to a feature request you made quite some time ago about using multiple settings for a single project. Based on our ESP-IDF Multiple config, you should achieve a similar result as you requested in #671

**Comment by SinglWolf** [comment]
> > > Hi @SinglWolf Could you please take a look at this?
> > > Tried to implement the project configuration feature. Take a look at the tutorial added here.
> > 
> > 
> > To be honest, I don't understand what this is about...
> 
> Is related to a feature request you made quite some time ago about using multiple settings for a single project. Based on our ESP-IDF Multiple config, you should achieve a similar result as you requested in #671

Now it's clear. I'm using a different product now. Maybe I'll try this one again soon.

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

Could we add some pop-up window to inform user that "Configuration saved successfully" ? 
Because once I click "Save" button there is no reaction from the program - so I don't understand if I actually create any configuration

**Comment by AndriiFilippov** [comment]
@brianignacio5 

It is also possible to add new project configuration without name. 


image

**Comment by SinglWolf** [comment]
> Hi @SinglWolf Could you please take a look at this?
> 
> Tried to implement the project configuration feature. Take a look at the tutorial added here.

Installed the extension. Launched `ESP-IDF: Open Project Configuration`... There are a lot of incomprehensible things. How to use all this? Why do I need to run a separate `ESP-IDF: Select project configuration` command to switch to a working configuration? Where is the configuration file stored? Is there documentation?
Thanks.

**Comment by brianignacio5** [comment]
Hi @SinglWolf there is a tutorial in [here](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/multiple_config.md) describing this.

The editor is to create project configurations and the other command to select specific one. These are saved as vscode workspace state.

**Comment by profeldoo** [comment]
> These are saved as vscode workspace state.

In a binary file (in VS Code Extensions Database in a hidden directory on my PC) that I cannot include into my project as a textual config file, which means each GitHub collaborator on my team has to manually configure his "Project Configurations" and go through all the steps described in "Multiple Config Tutorial". This also means these configs can go out of sync between different collaborators.

**Comment by brianignacio5** [comment]
We've made this PR related to moving this project configuration to an actual config file in #983 

You can try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/723888929.zip) which will saved the project configuration in a file in the current workspace folder.

**Pull request merged**
