### PR TITLE
Docs/update cmds

### LINKED ISSUE #1061: No warning when configuring extension on Linux and venv package not installed (VSC-1205)
### OS

Linux

### Operating System version

Ubuntu / WSL

### Visual Studio Code version

_No response_

### ESP-IDF version

5.2

### Python version

3.8

### Doctor command output

not applicable

### Extension

_No response_

### Description

When configuring extension on new setup of Ubuntu on WSL, it's necessary to install:

    sudo apt-get update
    sudo apt install python3-pip
    sudo apt install python3-venv

If these are not installed, extension will display a warning:

**"/usr/bin/python3 -m pip" is not valid (ERROR_INVALID_PIP)**

However it doesn't complain about missing **venv** up front. Instead it fails at the very end of the configuration process.

It would be nice if there was similar warning up front.

Note that if the users install **venv** after failure, and retry the process, they will encounter another issue:

**/home/zim/esp/esp-idf already exists. Delete it or use another location. (ERROR_EXISTING_ESP_IDF)**

and will have to manually delete the repo in order to restart.

### Debug Message

```plain
not applicable
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### LINKED ISSUE #1086: Errors in the configuration of the extension (VSC-1250)
### OS

Windows

### Operating System version

Windows 11

### Visual Studio Code version

1.84.2

### ESP-IDF version

5.1.2

### Python version

IDK, installed via ESP-IDF Setup

### Doctor command output

This command doesn't work for me. The message "ESP-IDF: Preparing ESP-IDF extension report" appears, but then nothing happens

### Extension

[esp_idf_vsc_ext.log.txt](https://github.com/espressif/vscode-esp-idf-extension/files/13463509/esp_idf_vsc_ext.log.txt)
I added .txt to the file name, because otherwise github refused to add it

### Description

When I configure the extension, there are errors in the output. There are no errors on the other computer.

```
spawn C:\Windows\system32\cmd.exe ENOENT
error: unable to create symlink porting/npl/riot/include/npl_syscfg/npl_sycfg.h: Permission denied
error: Submodule 'components/bt/host/nimble/nimble' could not be updated.
error: unable to create symlink examples/build_system/cmake/idf_as_lib/build-esp32.sh: Permission denied
error: unable to create symlink examples/build_system/cmake/idf_as_lib/build-esp32c2.sh: Permission denied
error: unable to create symlink examples/build_system/cmake/idf_as_lib/build-esp32c3.sh: Permission denied
error: unable to create symlink examples/build_system/cmake/idf_as_lib/build-esp32c6.sh: Permission denied
fatal: Could not reset index file to revision 'HEAD'.
Command failed: "C:\Users\Boris\.espressif\tools\idf-git\2.39.2\cmd\git.exe" reset --hard --recurse-submodule
```

These are just some mistakes. I saved the full output to a file
[esp uotput.txt](https://github.com/espressif/vscode-esp-idf-extension/files/13463527/esp.uotput.txt)

### Debug Message

```plain
-
```

### Other Steps to Reproduce

Steps to Reproduce:
1. Remove the extension
2. Delete folders `.espressif` `esp` and `.vscode\extensions\espressif.esp-idf-extension-1.6.5`
3. Install the extension
4. Open "configure ASP-IDF extension"
5. Start express installation

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

This PR address a few different issues:

- Rename NVS Partition Editor and Partition Editor commands names.
- Add button to enable custom partition if disabled when running Partition Editor command. This will update sdkconfig in the back.
- Add `venv` validation in Setup Wizard.
- Pass current workspace folder to setup wizard save settings.

Fixes #1061
Fixes #1086

## Type of change

Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "NVS Partition Editor" command. Check that names are changed.
2. Click on "Partition Table Editor" command. Check that names are changed. If custom partition table is not enabled for current project, a notification with a button to enable should appear and if clicked the custom partition table should be enabled in sdkconfig and the partition table editor should appear.
3. Run `ESP-IDF: Configure ESP-IDF` extension. Using workspace folder as save settings location (with idf.saveScope).
4. Use setup wizard in OS without python venv installed. See that the error notification is shown.
5. Observe results.

## How has this been tested?

Manual testing based on steps above.

**Test Configuration**:
* ESP-IDF Version: 5.0.4
* OS (Windows,Linux and macOS): macOS

## Checklist
- [ ] PR Self Reviewed
- [ ] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Review by radurentea — APPROVED** [review]
LGTM

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

1) After clicking "Enable" here 

image


the second notification ask to open sdk editor. 
image


I think we don't need double confirmation from user. 



2) if you try to open editor without project build, you get notification
image

but no hint at all here. We could add "Build project first" to this notification as well.

**Comment by brianignacio5** [comment]
> @brianignacio5 hi !
> 
> 1. After clicking "Enable" here
> 
> image
> 
> the second notification ask to open sdk editor. image
> 
> I think we don't need double confirmation from user.
> 
> 2. if you try to open editor without project build, you get notification
>    image
> 
> but no hint at all here. We could add "Build project first" to this notification as well.

This should be fixed. PTAL again

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi !

Tested under:
OS - Windows 10 

After clicking "Enable" here
image

getting this notification 
image


[esp_idf_vsc_ext.log](https://github.com/espressif/vscode-esp-idf-extension/files/14916088/esp_idf_vsc_ext.log)

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

Right click on .csv file in project -> The "NVS Partition Editor" still remains in the old format.

image

**Comment by brianignacio5** [comment]
> @brianignacio5 hi !
> 
> Right click on .csv file in project -> The "NVS Partition Editor" still remains in the old format.
> 
> image

Updated to new format

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

Run ESP-IDF: Configure ESP-IDF extension. Using workspace folder as save settings location (with idf.saveScope). -> still see the dropdown list during installation 

image

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

Tested under: 
OS - Windows 10 


Rename NVS Partition Editor and Partition Editor commands names. ✔️ 
Add button to enable custom partition if disabled when running Partition Editor command. This will update sdkconfig in the back. ✔️ 
Run ESP-IDF: Configure ESP-IDF extension. Using workspace folder as save settings location (with idf.saveScope). ✔️ 

If project hasn't built yet -> try to open Partition Table Editor -> good info message 👍 
image


LGTM 👍

**Review by AndriiFilippov — APPROVED** [review]

**Pull request merged**
