### PR TITLE
Feature/esp SBOM

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

Add support for `esp-idf-sbom` in the extension by running the `ESP-IDF: Run ESP-IDF-SBOM vulnerability check` command. 
Fixes VSC-1154

## Type of change

- New feature (non-breaking change which adds functionality)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Click on "ESP-IDF: Run ESP-IDF-SBOM vulnerability check"
2. Execute command. If **esp-idf-sbom** is not installed in python virtual environment it will be installed, a espidf.spdx file will be created and used to generated a report in a new terminal ESP-IDF SBOM. 
3. Observe results.

- Expected behaviour:

- Expected output:

## How has this been tested?

**Test Configuration**:
* ESP-IDF Version: 5.1
* OS (Windows,Linux and macOS): Windows MacOS

## Dependent components impacted by this PR:

- Component 1
- Component 2

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [x] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 

Tested under: 
OS - Windows 10 
ESP-IDF: v5.1.2 

1) Run command "ESP-IDF: Run ESP-IDF-SBOM vulnerability check" without built project - do see notification message about it : 
image

2) Run command "ESP-IDF: Run ESP-IDF-SBOM vulnerability check" with built project - do see SBOM report generated and output in SBOM terminal.  👍  

3) Should we add SBOM functions that are already present in Eclipse? like choosing SBOM file location and so on ? 

4) After SBOM report is generated - open the report file - it is empty - it tooks some time for data to appear in the file, like ~ **20sec**  and it might be a bit confusing for users since there is no "progress bar" running or any notification message at all.  Do you think we can do something with that @kolipakakondal ?

**Comment by brianignacio5** [comment]
Added `idf.sbomFilePath` configuration setting to set the resulting sbom file path and wrap the task into a progress vscode api.

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi ! 


If I attempt to create a new .txt file or overwrite an existing one, I receive a notification stating "PATH exists" and am prevented from proceeding.

image

**Comment by brianignacio5** [comment]
Updated it to check if path exists, if is a directory or is not writable then the error will be shown.

**Comment by AndriiFilippov** [comment]
@brianignacio5 hi !

Tested
LGTM 👍

**Review by AndriiFilippov — APPROVED** [review]

**Pull request merged**
