### PR TITLE
use absolute build path over workspace relative

### LINKED ISSUE #786: [Feature Request]: Allow setting a custom build path by conf setting (VSC-953)
**Is your feature request related to a problem? Please describe.**
As the build is heavy on disk usage, it is, depending on the project, very slow.
The #668 work allows setting a custom build folder, but relative to the workspace.

**Describe the solution you'd like**
Being able to set a custom build path, that for speed, would be on a [RAM Drive](https://en.wikipedia.org/wiki/RAM_drive).

**Describe alternatives you've considered**
Moving the entire project to a RAM Drive.

**Additional context**
For testing on Windows, one could use the [ImDisk Toolkit](https://sourceforge.net/projects/imdisk-toolkit/)

### PR DESCRIPTION
**Pull request by brianignacio5**
## Description

Use `idf.buildPath` as absolute build path instead of relative path.

Fixes #786 

## Type of change

- New feature (non-breaking change which adds functionality)

## How has this been tested?

Run existing extension commands and test the behavior has not changed.

- Manual Test

**Test Configuration**:
* ESP-IDF Version: v4.4.2
* OS (Windows,Linux and macOS): macOS

## Checklist
- [x] PR Self Reviewed
- [x] Applied Code formatting
- [x] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by project-x51** [comment]
This change is not working for me yet. As per our conversation in https://github.com/espressif/vscode-esp-idf-extension/pull/668

**Comment by brianignacio5** [comment]
Any updates @project-x51 ?

**Comment by project-x51** [comment]
Hi Brian. Do you have a revised vsix installer?

**Comment by brianignacio5** [comment]
Try this one [here](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/376403069.zip) @project-x51

**Comment by project-x51** [comment]
Better. The idf.buildPathWin works on my windows system. The idf.buildPath does not.

Building & flashing works. When I click on the monitor icon it tries building the project again in the default path. "${workspaceFolder}\\build".

NOTE: I am able to Unix style path for the parameter.

**Comment by project-x51** [comment]
It does build to and flash from my RAM disk.

**Comment by brianignacio5** [comment]
@project-x51 I've added the fixes for IDF Monitor in [here](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/379148097.zip) PTAL

**Comment by project-x51** [comment]
Cool, it builds, flashes and monitors. 

I'm having issues debugging though. When I try to start OpenOCD it fails on an ESP32-S3 using JTAG via USB.

```
[OpenOCD]
Open On-Chip Debugger  v0.11.0-esp32-20220411 (2022-04-11-08:48)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
[OpenOCD]
debug[OpenOCD]
_level: 2

[OpenOCD]
Info : only one tra[OpenOCD]
nsport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set[OpenOCD]
 to 0x303a and PID to 0x1002
Info : esp_usb_jtag: capabilities descr[OpenOCD]
iptor set to 0x30a
Info : esp_usb_jtag: target chip id set to 9
[OpenOCD]
Warn : Transport "jtag" was already selected
[OpenOCD]
Info : Listening on po[OpenOCD]
rt 6666 for tcl connections
Info : List[OpenOCD]
ening on port 4444 for telnet connections
[OpenOCD]
❌ Error: [OpenOCD]
esp_usb_jtag: could not find or open device!

Assertion failed!

Program: C:\esp\tools\openocd-esp32\v0.11.0-esp32-20220411\openocd-esp32\bin\openocd.exe
File: ../src/jtag/core.c, Line 338

Expression: jtag_trst == 0
[OpenOCD]
[Stopped] : OpenOCD Server
```

If I Start OpenOCD from the terminal using the command "opencod -f board/esp32s3-builtin.cfg" then I am able to start OpenOCD. However I cannot start a debug session. 

I get the prompt "Failed to init Debug Adapter!"

I'm not sure why OpenOCD isn't starting from the button in VsCode but I'm guessing it cant start the debug session because its looking in the wrong place for the .elf files.

```
{
  "C_Cpp.intelliSenseEngine": "Tag Parser",
  "idf.portWin": "COM6",
  "idf.adapterTargetName": "esp32s3",
  "idf.openOcdConfigs": [
    "board/esp32s3-bridge.cfg"
  ],
  "idf.flashType": "JTAG",
  "idf.buildPathWin": "R:/hello_world/build"
}
```

**Comment by brianignacio5** [comment]
@project-x51 You could increase the debug adapter logLevel in the `.vscode/launch.json` to see more details about why is the debug adapter is failing. As you can see in the PR, the debug adapter is getting the elf file path from the proposed setting.

**Pull request merged**
