### PR TITLE
Bugfix/bin flashing

### PR DESCRIPTION
**Pull request by brianignacio5**
Fix storage partition bug by adding the partition storage in the flash model and flash_files to flashSections.

### CODE REVIEW

**Comment by edouardreg** [comment]
Hello, I have notice that my storage.bin is no more flashed as before in my strorage partition : will this function be enabled again soon ?
Regards,  Edouard

**Comment by brianignacio5** [comment]
Hey @edouardreg yes this is the fix for this issue

**Comment by edouardreg** [comment]
Thanks Brian, but sorry, I'm not very experimented with github : how can I apply this fix ?

**Comment by brianignacio5** [comment]
This PR has a vsix (extension installer) and this is the [download link](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/59512490.zip)

**Comment by edouardreg** [comment]
Thanks again : it's ok now with this version. The storage.bin is perfectly flashed into storage partition.

**Pull request merged**
