### PR TITLE
Remove trailing comma in settings.json template file (VSC-504)

### LINKED ISSUE #239: Create project using example <any example> - error when copying (VSC-503)
Screenshot from 2020-12-18 09-07-57

IDF-Version: 4.3 (master branch) - all packages up-to-date
ArchLinux
Fresh install and configuration of VSCode-ESP-IDF-Extension 0.5.1

extension log entry when it happens:
```
{"message":"Error copying ESP-IDF example.","stack":"SyntaxError: /home/neal/esp32_examples/ulp/.vscode/settings.json: Unexpected token } in JSON at position 231\n\tat JSON.parse (<anonymous>)\n\tat /home/neal/.vscode/extensions/espressif.esp-idf-extension-0.5.1/dist/extension.js:8:467699\n\tat /home/neal/.vscode/extensions/espressif.esp-idf-extension-0.5.1/dist/extension.js:1:53675\n\tat FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)","level":"error","timestamp":"2020-12-18T15:03:48.487Z"}
```

### PR DESCRIPTION
**Pull request by meltdown03**
fixes #239

### CODE REVIEW

**Review by pwmb — APPROVED** [review]

**Comment by meltdown03** [comment]
I get a lot of unrelated IntelliSense suggestions when using the "Fuzzy" `Tag Parser` engine. Would this be a better alternative:
```
"C_Cpp.intelliSenseEngine": "Default",
"C_Cpp.intelliSenseEngineFallback": "Enabled"
```

It gives context-aware results with the "Default" engine, and "Tag Parser" as a fallback if there are #include errors according to the IntelliSense docs.

C_Cpp.intelliSenseEngine:
```
Controls the IntelliSense provider. "Tag Parser" provides "fuzzy" results that are not context-aware. "Default" provides context-aware results. "Disabled" turns off C/C++ language service features.
```

C_Cpp.intelliSenseEngineFallback:
```
Controls whether the IntelliSense engine will automatically switch to the Tag Parser for translation units containing #include errors.
```

**Comment by meltdown03** [comment]
I found the best combination is to use `Default` engine, `Enabled` fallback, and most importantly, Install the CMake Tools extension from Microsoft and set it in `c_cpp_properties.json` as the `configuartionProvider`: 
```
Name: CMake Tools
Id: ms-vscode.cmake-tools
Description: Extended CMake support in Visual Studio Code
Version: 1.5.3
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools
```
Now I get only the exact definitions/declarations and all references are found.

**Comment by brianignacio5** [comment]
I added this fix earlier in #229 (maybe you missed it) as shown in https://github.com/espressif/vscode-esp-idf-extension/pull/229/files#diff-811af28ba89f8a78de614774dcd9fcf07a855803a0c1261bb2e49370254e3a59 

Thanks for testing this @meltdown03 Will try it with CMake Tools extension and maybe add it as this extension dependency.

**Comment by meltdown03** [comment]
> I added this fix earlier in #229 (maybe you missed it) as shown in https://github.com/espressif/vscode-esp-idf-extension/pull/229/files#diff-811af28ba89f8a78de614774dcd9fcf07a855803a0c1261bb2e49370254e3a59
> 
> Thanks for testing this @meltdown03 Will try it with CMake Tools extension and maybe add it as this extension dependency.

Should I close this PR then?

**Pull request merged**
