### PR TITLE
Codicons in sdkconfig editor (VSC-467)

### PR DESCRIPTION
**Pull request by brianignacio5**
Replace font awesome icons to prefer vscode codicons in SDKConfig Editor.

Current onboarding still depends on font-awesome and should be replace after #159 is merged.

### CODE REVIEW

**Comment by pwmb** [comment]
Lets move b43cfd5f85560e47268a34071ad245f41c45fbfd from this PR to a new PR, because updating to `codicons` should be done in a separate PR together with all other webviews and pending PR like Onboarding, Partition Table editor can then also use `codicons` as well.

**Comment by brianignacio5** [comment]
Should we remove font awesome in Onboarding ? I ask because #159 will remove Onboarding and already uses vscode-codicons

**Comment by pwmb** [comment]
So we can remove all the `font-awesome` dependencies from our project and search for `fa` or `fas` etc class name and replace with `codicon` classes.

So yes from onboarding, idf_size, menuconfig, heap_tracing etc... 

For onboarding, we can keep the font-awesome and codicons together... but later we can remove from all

**Review by pwmb — APPROVED** [review]
LGTM

**Pull request merged**
