### PR TITLE
Feature/launch monitor with debug session

### PR DESCRIPTION
**Pull request by brianignacio5**
`idf.launchMonitorOnDebugSession` configuration setting to launch IDF Monitor when ESP-IDF debug session starts, default is true.

If launched by debug session, the IDF Monitor will be disposed on end of debug session.

### CODE REVIEW

**Comment by meltdown03** [comment]
The IDF Monitor opens after the debugger starts which causes the chip to reset. That causes the debugger to freeze up and errors when trying to step or resume:

``` bash
Open On-Chip Debugger  v0.10.0-esp32-20201202 (2020-12-02-17:38)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
adapter speed: 20000 kHz

Info : FreeRTOS creation
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 20000 kHz
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s2: Target halted, PC=0x40088F38, debug_reason=00000001
Info : Detected ESP32-S2 chip
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
Warn : No symbols for FreeRTOS!
Info : esp32s2: Target halted, PC=0x400314BA, debug_reason=00000001
Info : Flash mapping 0: 0x10020 -> 0x3f000020, 102 KB
Info : Flash mapping 1: 0x30020 -> 0x40080020, 511 KB
Info : esp32s2: Target halted, PC=0x400314BA, debug_reason=00000001
Info : Auto-detected flash bank 'esp32s2.flash' size 4096 KB
Info : Using flash bank 'esp32s2.flash' size 4096 KB
Info : esp32s2: Target halted, PC=0x400314BA, debug_reason=00000001
Info : Flash mapping 0: 0x10020 -> 0x3f000020, 102 KB
Info : Flash mapping 1: 0x30020 -> 0x40080020, 511 KB
Info : Using flash bank 'esp32s2.irom' size 512 KB
Info : esp32s2: Target halted, PC=0x400314BA, debug_reason=00000001
Info : Flash mapping 0: 0x10020 -> 0x3f000020, 102 KB
Info : Flash mapping 1: 0x30020 -> 0x40080020, 511 KB
Info : Using flash bank 'esp32s2.drom' size 104 KB
Info : JTAG tap: esp32s2.cpu tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s2: Debug controller was reset.
Info : esp32s2: Core was reset.
Info : esp32s2: Target halted, PC=0x40007299, debug_reason=00000000
Info : esp32s2: Core was reset.
Info : esp32s2: Target halted, PC=0x40000400, debug_reason=00000000
Info : esp32s2: Target halted, PC=0x400314BA, debug_reason=00000001
Info : Flash mapping 0: 0x10020 -> 0x3f000020, 102 KB
Info : Flash mapping 1: 0x30020 -> 0x40080020, 511 KB
Info : Using flash bank 'esp32s2.irom' size 512 KB
Info : esp32s2: Target halted, PC=0x400314BA, debug_reason=00000001
Info : Flash mapping 0: 0x10020 -> 0x3f000020, 102 KB
Info : Flash mapping 1: 0x30020 -> 0x40080020, 511 KB
Info : Using flash bank 'esp32s2.drom' size 104 KB
Info : dropped 'gdb' connection
Info : accepting 'gdb' connection on tcp/3333
Info : esp32s2: Target halted, PC=0x40088F38, debug_reason=00000001
Info : esp32s2: Debug controller was reset.
❌ Warn : esp32s2: target not halted
Error: esp32s2: Failed to prepare for resume!
Info : target esp32s2 was not halted when resume was requested
```

Can the monitor be set to start before the debugger or just not reset the chip?

**Comment by brianignacio5** [comment]
The monitor is called before connecting to debug adapter server and should be called before debug session start, thanks for noticing it.

**Comment by meltdown03** [comment]
Yeah, the monitor starts up first but takes a few seconds to setup the environment and stuff. By then, the debugger is loaded, and when the monitor starts, it resets the board.

**Comment by brianignacio5** [comment]
Please try again now, the debug server connection should wait for createMonitor to resolve.

**Comment by meltdown03** [comment]
It works now

**Review by pwmb — APPROVED** [review]
LGTM

**Pull request merged**
