### PR TITLE
Feature/hints viewer v2

### PR DESCRIPTION
**Pull request by radurentea**
## Description

Added Hints Viewer. Hints are provided in yaml file from esp-idf folder: <ESP-IDF FOLDER>/tools/idf_py_actions/hints.yml
There is a bottom panel now called "ESP-IDF" which displays the hints and errors automatically based on the issues the user current have in the file that he has open in text editor. There is also a button which user can use for manual searches.
User can also see the hints if he hovers over the red squiggly lines in the text editor.

This is the same implementation as in https://github.com/espressif/vscode-esp-idf-extension/pull/1031, but created another PR because the branch was too old and had too many conflicts to solve.

## Type of change

Please delete options that are not relevant.
- New feature (non-breaking change which adds functionality)

## Steps to test this pull request

Provide a list of steps to test changes in this PR and required output

1. Open ERROR HINTS bottom panel:
image

2. Press on "ESP-IDF: Search Error Hint" 
image

3. Paste error in the top input that shows up
image

- Expected behaviour:
Hints shown in the panel
image

## How has this been tested?

Followed the steps above on a windows OS.

**Test Configuration**:
* ESP-IDF Version: 5.1.1
* OS (Windows,Linux and macOS): Windows

## Checklist
- [ ] PR Self Reviewed
- [x] Applied Code formatting
- [ ] Added Documentation
- [ ] Added Unit Test
- [ ] Verified on all platforms - Windows,Linux and macOS

### CODE REVIEW

**Comment by radurentea** [comment]
@brianignacio5 and @AndriiFilippov PTAL

**Review by brianignacio5 — APPROVED** [review]
LGTM

**Comment by AndriiFilippov** [comment]
@radurentea hi !

Create a "Hello World" project -> add string [#import "spiram.h"] -> build -> get error "spiram.h: No such file or directory" -> call "ESP-IDF: Focus on Error Hints View" " -> execute hint search automatically -> able to see hints ✔️ 

image

LGTM 👍

Have a couple of thoughts: 

1) since `ESP-IDF: Focus on Error Hints View` search for hints automatically, why do we need `ESP-IDF: Search Error Hint `  ??

2) Feature seems nice, but it is like a bit hidden from user. Maybe should we add icon to `Tool Bar` , or maybe something else  ? 
or even link to execute `ESP-IDF: Focus on Error Hints View` somewhere here ? 

image

**Comment by radurentea** [comment]
> 1.since ESP-IDF: Focus on Error Hints View search for hints automatically, why do we need ESP-IDF: Search Error Hint  ??
- That was the first implementation and I've just kept it, maybe there is some use for some users.

> 2.Feature seems nice, but it is like a bit hidden from user...
- I think we can add it to the Walkthrough we've discussed and/or create a list of features where we can display it in the documentation / welcome page

We can create a ticket for improvement to keep track of your feedback and maybe in the future we will also receive some feedback from the users.

**Pull request merged**
